require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
plugin 'cocoapods-user-defined-build-types'

enable_user_defined_build_types!

platform :ios, '14.0'
install! 'cocoapods', :deterministic_uuids => false

ENV['RCT_NEW_ARCH_ENABLED'] = '0'

target 'ReactNativeExample' do
  config = use_native_modules!

  pod 'Rownd', :path => '/Users/michaelmurray/Documents/iOS/ios'
  pod 'Sodium', :build_type => :dynamic_framework
  pod "Get", :path => '/Users/michaelmurray/Documents/iOS/Get'
  pod 'LBBottomSheet', :path => '/Users/michaelmurray/Documents/iOS/LBBottomSheet'
  pod 'CodeScanner_Rownd', :path => '/Users/michaelmurray/Documents/iOS/CodeScanner'

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
